testing

diff --git a/.github/workflows/terraform-template.yml b/.github/workflows/terraform-template.yml
--- a/.github/workflows/terraform-template.yml
+++ b/.github/workflows/terraform-template.yml
@@ -65,6 +65,16 @@ jobs:
       
       - name: correct format
         run: terraform fmt
+      
+      - name: Debug ACCESS_KEY
+        run: |
+          echo "Checking if ACCESS_KEY is set..."
+          if [[ -z "${ACCESS_KEY}" ]]; then
+          echo "ERROR: ACCESS_KEY is empty or not set!"
+          exit 1
+          else
+          echo "ACCESS_KEY is set."
+          fi
 
       - name: Initiate terraform
         run: |
