update

diff --git a/.github/workflows/terraform-template.yml b/.github/workflows/terraform-template.yml
--- a/.github/workflows/terraform-template.yml
+++ b/.github/workflows/terraform-template.yml
@@ -66,7 +66,7 @@ jobs:
       
       - name: Check ACCESS_KEY Format
         run: |
-          echo "${ACCESS_KEY}" | base64 --decode > /dev/null || echo "ERROR: Invalid Base64!!"
+          echo "${ACCESS_KEY}" | base64 --decode > /dev/null || echo "ERROR: Invalid Base64!"
 
       - name: Initiate terraform
         run: |
